### ISSUE TITLE
Computers to be disabled

### ISSUE THREAD

**Issue by orgitnized** [EvotecIT/CleanupActiveDirectory#1]
When I run the script for the purposes of reporting, I thought it would list all the computers it would disable, but it does not. Maybe I'm misunderstanding portions of it.
I thought the report showed everything, but when you run a disable option, it would limit it to a specific number.

```
PS C:\Users\Administrator> $Output = Invoke-ADComputersCleanup -Disable -ShowHTML
[i] [CleanupActiveDirectory] Version [Informative] Current/Latest: 1.0.0 at 03/05/2023 13:52:03
[i] Started process of cleaning up stale computers
[i] Executed by: administrator from domain example.COM
[i] Getting all computers for domain example.com
[i] Computers found for domain example.com: 43
[i] Processing computers to disable for domain example.com
[i] Looking for computers with LastLogonDate more than 180 days
[i] Looking for computers with PasswordLastSet more than 180 days
[i] Computers to be disabled for domain example.com: 33. Current disable limit: 1
[i] Starting process of disabling computers for domain example.com
[i] Disabling computer exampleserver1$ DN: CN=exampleserver1,CN=Computers,DC=example,DC=com Enabled: True Operating System: Windows Server 2008 R2 Standard LastLogon: 04/21/2019 09:31:26 / 1417 days, PasswordLastSet: 04/14/2019 06:17:43 / 1424 days
[+] Disabling computer CN=exampleserver1,CN=Computers,DC=example,DC=com (WhatIf: False) successful.
[i] Cleanup process for processed computers that no longer exists in AD
[i] Exporting Processed List
[i] Summary of cleaning up stale computers
[i] Computers to be disabled for domain example.com: 33
[i] Computers pending deletion:0
[i] Computers disabled in this run: 1
[i] Generating HTML report
[i] Finished process of cleaning up stale computers

```

I thought when the report would show, it would show me 33 computers, but it doesn't.
The script will disable a single computer - ok.
If I run it again, it will just detect the same computer again, which is already disabled.
I figured since it was already disabled, it would move on to a computer out of that 33 detected, that still needs to be deleted.
Running the report without disabling or deletion, I thought would display everything and ignore limiters in disabling or deleting, but it seems to still just show me one computer, all the time.
Thanks for any help!

**Comment by PrzemyslawKlys** [comment]
I've found the bug. The processed list was never loading. I'll fix it and also improve reporting.

**Comment by PrzemyslawKlys** [comment]
Fixed in:
- https://github.com/EvotecIT/CleanupActiveDirectory/releases/tag/v1.1.1
